// <auto-generated />
namespace EntityCodeFirst.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class InitialCreate : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "202410150657592_InitialCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAN1YzY7bNhC+F+g7CDy1h5jOFgiShZzA9WYLI/VuEG1yp6Wxl1iKUklqYT9bDn2kvkKH+uXSsmXvJk2Tm0XPfPPND2dG+ufz3+GbTSqCe1CaZ3JCno/GJAAZZwmX6wkpzOrZS/Lm9c8/hW+TdBN8auTOrBxqSj0ht8bk55Tq+BZSpkcpj1Wms5UZxVlKWZLRs/H4JX0+poAQBLGCIPxQSMNTKB/wcZbJGHJTMLHIEhC6Psd/ohI1uGIp6JzFMCFvUdNsZyh3yZU2o+qZBFPBGbKJQKxOpDZ+ZamR1iiarUBvtjmUpifkoyqkK4Ey72D74ACP3qssB2W2H2Dl6M0TEtCHutRXblU9PUthQubS/HZGgqtCCLYUeLBiQgMJ8hfnkckU/AESFDOQvGfGgMIEzROo41KG4jx/cVw0XtHxmY0GZVJmhhnM9g75HqrTlmpkFJYOCS75BpI/Qa7NbUt3wTbNCf4kwUfJsdJQyagCXPeq52GzC6bu2Dex/A6jvc4U/ybGMed3Q6XhooS0q+eDVd569YhKb3QfU+2u7ndQ8Q3dr171hxOHXdMwjnGoadln2BgveZVsBMYpIE2CDrjqmaOyw/mO+8qN530A3ZXoc6El2/V2WjX3ZgjQPVMgXLA8x+g6U6E+CaJqJMyeRae3/LTCoLHu6fwt29YSFh1bg/evjXk9hy6YYUtm8z1L0h6xg6lprLgZ8m9cF+9G2v6uNPpn4mh3aLnRu0SHUrwzpW/QcumbdbViFDPB1J5JNctEkcpDU28IZdqDMj0ZpZ4JPlB9fBpWV9I+XH+xDyNWrdtHq053kULq5covCrpTFV7n9UvsqALsbvkXKML+mVKiDRXiftV9IXYHiRvk/cPpGDS/MN3z/zhpO+3UF2mtt23Va59h3cqGN+2d3laJkADDdM8T29eirTaQjqzAKPpLzARHfzuBBZN8BdrcZHdg3xqw9T5+UW8HtdaJ+D9v69yGYHBLObixDW3Z8p6p+JapX1K2+fXJm/OT0fxt+MmA7oZbhvNH22+/So3s7qUnJOLUXdPfe4a3zr1LZ9VXJiRZZki8IlivqUfuowfX0T54Z5F95La620ZD6n7WCC9A83UHYT9ySIjt+0UH2sjM5SprkoneuYwaES/XCzAswdhPleErFhv8Owaty7eQT0wUdiCnS0jm8roweWGmWkO6FFvX35Aetl+u5A85h9e5fdJfwgWkydEFuJa/F1wkLe/Lnhu+B8KWYX2BkBW+hdm0blukq0weCVSH7wJykPb63UCaCwTT1zJi97Cf23AMH0YsvOBsrVjqRrA6qZlEDC07JtCAq9HZs1/lqP0s9/pfBNDQgMgTAAA="; }
        }
    }
}
