// <auto-generated />
namespace EntityCodeFirst.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class KategoriAdiToKategoiAdInKategorisTable : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "202410230924200_KategoriAdiToKategoiAdInKategorisTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEANVazW7jNhC+F+g7CDq1BdZyUmCxG9i7cJ2kMLZOgijZa8BItE2EolSSCuxn66GP1FfoUL8UJVmW7WySW0RyPs7PN+RwnP/++Xf0dR1Q6xlzQUI2tk8GQ9vCzAt9wpZjO5aLD5/sr19+/ml04Qdr63u+7lStA0kmxvZKyujMcYS3wgESg4B4PBThQg68MHCQHzqnw+En52ToYICwAcuyRrcxkyTAyQd8TkPm4UjGiM5DH1ORjcOMm6BaVyjAIkIeHtsXICk3U1h3SbiQg/TbtiaUINDGxXTRU7XhZ6WaXWwK26agd5sIJ1uP7XseM30FrPmGN5UBGLrhYYS53NzihSY3823Lqco6pnAhasgpFcb2jMnfT23rKqYUPVIYWCAqsG1FH89cGXL8J2aYI4n9GyQl5hCgmY8zvySuOIs+7uaNz87wVHnDQYyFEkmIdk35BlUnhaqu5EAd27oka+z/hdlSrgp152idj8CftnXPCDANhCSPsW5e+t297RzxJ/QqO38Dby9DTl5lc4j5Uxc1DJQr9EyWSTgNvNKQW0yTBWJFojSPBvnkg9pVgHU8DG5DqomlMw93iC+xBJ3Cxmk3jLlnKDVyyiTbmnqFhnukXy67Twrqsu8gDXN1f0QqtrIp48khVMq50kKlnGl7UWkeC4jLXkzKRPchkib6DniUafsKJ3q28z17Ruy1NnfxivAX3ryNrhMhQo8kQTJyOkuaqgEXzLe2Z1BqhJ59oHdMJYko8UCBsT0cDE5qnmkFLk75EjipiwzQ30xzNcPq6Qm1n0QECJ/ZrL7xWtaMVWtdLKsHTenIij41g6rCuVlNAKWnOkAywjRh5MeMCaH5oa5MfjBqi5qPTvOs6uRBoXnFcmdnnDzsGk6mq3kSVg1soHwR7LLCd9ISP38KOC1vgdEcRRFko/Y2yEYsN30YTD+4/Qv/IMVwPNFQ/xfaFjvB6YyW2JhVnM1eI+dIokekzoepHzQs20rtfBed4fUg5VzLV6u/U4nml9Gg/nTRvXcJBgVwuSS2YSPEdbHkSYYo4i3vlWlI44Bte/t0oUwaUCa9UbKXgQmUDffDKo8EE67tsOhCTAt4Ey0drSONHCNWJimcGiuMvDQpthMBy7PiCCRsLuITtC4itou2uViv3HUnt78GdkEziamPv5mgFbfSEWLWWC3vFLJWyTYfayWy7uLWonsHLDNc2nBvrKwkbYDLZnojZnVmA2I28+MZVb28m8+CvEjZOd9zgV1uF1WBtORetaKpu2avY+Bh23mgvFVo01vRrGTaUdE+l+dWvaDA8EnyfpgJ9QIpXis9zTcruTpfagWduaRga1HYGQXcKCumuju+teoqXWJb4IZn4qvKyt1A7gQDtWDg/k2nlEB+lAvmiJEFFvIufMKqew3F3/4N4+JNLYRP33LXmCgXdDYUujqHW7u9cPpxb4X4LwFa/3pwB/dgNLMrezCg3mlN3NnTW4251gi3e5vgDTdIX4Rx9cZmj7C+t9bgi3iw1tI7KC+a2nTHAKy03o4Q4oPbacfooKX9qH4NM/X7KF5grqKNKNywQnK4Y2v13g0nzCMRoqbe9bKjT+IrjxbQ5sw5jjBTPNTt67NfR9FV4BuJ1OWQ3k1Gs2HT3W5s7Tam5cjY9h9DCHVK0+YGWVsjcmsfsgm+tY/X1qbc1qVs2qDsbr5SD7Oxbbm1a6nHqHxjvEiPsl66AkO1f2mANBFkWUKowpxhr8LNYs2MLcI8XwyN8iXmgYkl8oG4Ey7JAnkSpj0sRPJbxXdEY/UsCx6xP2PXsYxiCSbj4JFudGeoVNu2f9KIreo8uo6SH/WOYQKoScAEfM3+iAn1C70v6/dZG4TK4eySVLGU6rJcbgqkq5DtCJS5rzh67nAQUQAT18xFz7hdt24fVj02OidoyVGgezAdyTRxEeysbQEb6BLlfvAJdPWD9Zf/AYMP+BvEIwAA"; }
        }
    }
}
