// <auto-generated />
namespace EntityCodeFirst.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class RenameKategoriAdToKategoryAdiInKategorisTable : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "202410230921220_RenameKategoriAdToKategoryAdiInKategorisTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEANVazW7jNhC+F+g7CDq1BdZyUmCxG9i7cJ2kMLZOgijZa8BItE2EolSKCuxn66GP1FfoUL8URVmW7WySW0RyvvkfDsf5759/R1/XAbWeMY9JyMb2yWBoW5h5oU/YcmwnYvHhk/31y88/jS78YG19L86dynNAyeKxvRIiOnOc2FvhAMWDgHg8jMOFGHhh4CA/dE6Hw0/OydDBAGEDlmWNbhMmSIDTD/ichszDkUgQnYc+pnG+DjtuimpdoQDHEfLw2L4ASrGZwrlLwmMxyL5ta0IJAmlcTBc9RRt+lqLZJVNgm4HebSKcsh7b9zxh6gk48w1vaguwdMPDCHOxucULhW7m25ZTp3V04pJUo5MijO0ZE7+f2tZVQil6pLCwQDTGthV9PHNFyPGfmGGOBPZvkBCYg4NmPs7tkpriLPq4mzU+O8NTaQ0HMRYKJMDbDeENok5KUV3BIXRs65Kssf8XZkuxKsWdo3WxAn/a1j0jEGlAJHiCVfWy7262c8Sf0Ktw/gbWXoacvApz8PlTV2hoKFfomSxTd2p4lSK3mKYH4hWJsjwaFJsPkmsM2vEwuA2pQpbtPNwhvsQCZAqN226YcE8TauRUSbY19UoJ90i/gnafFFRp30EaFuJO/B8QlK3hlAfKIbFUBEtLLBWhtlcszZMYHLNXKOWk+0SSQvoOAimX9hVKes75nj0j9lrMXbwi/IWZt4XrJI5Dj6RO0pI6T5q6AhfMt7ZnUKaEmn0gd0IFiSjxQICxPRwMThqWaQUuy3wFnDZGGuhvurqKYs30hOZPIAIBn+ssv/FaNJSVZ10s6oWmMmRNnoZCdeJCLRNAZakOkDxgTBhFmdEhFDs0hSkKo3LIXDr1WtUZB6XkNc2dnXEKtys4uax6JawraAj50tlVi+9kPX7xFnBaHgOjOYoiyEblcZCvWG72Mph+cPt3/kGG4Xix4QFQSltyguqMlljblTGbP0fOkUCPSNaHqR8Yjm0N7YKLGuFNJxWxVpyWf2cU5qfRoPl2Ua13CQoFcLmkumHNxU2y9E2GKOItD5ZpSJOAbXv8dKFMDCiT3ij500AHypf7YVUlQYdrKxZdiFkHr6Nlq02kkaP5Sg8KpxEVWl7qIbZTAFa14ghBaO7iU7SuQGwnbTOx2rqrRm5/DuyClnbWJrh04824rbyXjuA1Y7+8k9NaKdusrDTJqo1b2+4dsPRKoiz3xsqbUgNcvtMbMe80DYj5zo+PqPr1ba4GRZuyc8YXBLvcL7IHacm+ek/TNM1eheBhW0WQ1iql6S1o3jTtKGif63OrXNBi+CR9Qcxi+QYp3ys91dd7uWa8NFo6/UgZrWVrp7Vwo7yd6h76Nvqr7IhtgRmeiS97K3cDuRMM5IGB+zedUgL5UR2YI0YWOBZ34ROWA2xo//afGZev6jj26VseHBNpgs6RQtfwcOvAF6of91aI/xKg9a8HD3EPRtMHswcDqsPW1Jw9rWXMNSPc7oOCNzwjfZGIM8w2e/j1vU0HX8SEjaneQYlhmtQdA7A2fTuCiw+eqB1jiJaNpPrNzORvpHiBufQ2onDFxoLDJdto+G44YR6JENXlbvYdfTJfWrSE1nfOcYSZjENVvz78OrquEl9LpC6D9J4z6jOb7olj68Ax60fGtv8YgquzMDXPyNpmkVtHkSb41lFe26Ry26DSxKAacL7SGNM4udw6uFR9VD0yXmRM2exdIUKVf2uANInJsoKQnTnDXi02yzMztgiLfNEkKo7oBRML5EPgTrggC+QJ2PZwHKc/V3xHNJHvsuAR+zN2nYgoEaAyDh7pRjWGTLVt/NNZbF3m0XWU/q53DBVATAIq4Gv2R0KoX8p92bzP2iBkDueXpPSlkJflclMiXYVsR6DcfGXpucNBRAEsvmYuesbtsnXbsG6x0TlBS44C1YLZSi6Ji4CzwgIYqBQVP/iEcPWD9Zf/AbxmzZ/IIwAA"; }
        }
    }
}
